import sys
import re
import argparse
from gpatcher.core.common import Colors, log_err
from gpatcher.core.create import invoke_create
from gpatcher.core.apply import invoke_apply
from gpatcher.core.restore import invoke_restore
from gpatcher.core.verify import invoke_verify
from gpatcher.core.doctor import invoke_doctor
from gpatcher.core.update import invoke_update
from gpatcher.ia.client import invoke_upload, invoke_search, invoke_fetch
from gpatcher.tui import invoke_interactive_menu

def main(args=None):
    if args is None:
        args = sys.argv[1:]

    # If no arguments are passed, default to launching the interactive menu (TUI)
    if len(args) == 0:
        invoke_interactive_menu()
        return 0

    parser = argparse.ArgumentParser(
        prog="gpatcher",
        description="gpatcher -- Game Delta Patching Dashboard & CLI"
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Available subcommands")

    # create
    create_parser = subparsers.add_parser("create", help="Generates a delta patch package between two directories")
    create_parser.add_argument("--old", required=True, help="Old version directory")
    create_parser.add_argument("--new", required=True, help="New version directory")
    create_parser.add_argument("--game", required=True, help="Name of the game")
    create_parser.add_argument("--old-ver", help="Old version label (auto-detected if omitted)")
    create_parser.add_argument("--new-ver", help="New version label (auto-detected if omitted)")
    create_parser.add_argument("--out", default=".", help="Output directory for the patch bundle")
    create_parser.add_argument("--exclude", default="", help="Comma or semicolon separated exclusion pattern")

    # apply
    apply_parser = subparsers.add_parser("apply", help="Applies a patch package to a target directory")
    apply_parser.add_argument("--patch", required=True, help="Local patch ZIP path or URL")
    apply_parser.add_argument("--target", required=True, help="Target game installation directory")
    apply_parser.add_argument("--dry-run", action="store_true", help="Perform pre-flight verification only")
    apply_parser.add_argument("--no-backup", action="store_true", help="Disable backup generation")
    apply_parser.add_argument("--keep-backup", action="store_true", help="Keep backup directory after successful apply")

    # restore
    restore_parser = subparsers.add_parser("restore", help="Restores target directory using a stashed backup")
    restore_parser.add_argument("--target", required=True, help="Target game installation directory")
    restore_parser.add_argument("--backup", default="latest", help="Backup folder name or 'latest'")
    restore_parser.add_argument("--keep-backup", action="store_true", help="Keep the backup folder after restoring")

    # upload
    upload_parser = subparsers.add_parser("upload", help="Uploads a game patch bundle to the Internet Archive")
    upload_parser.add_argument("--patch", required=True, help="Path to local patch bundle ZIP")
    upload_parser.add_argument("--creator", default="anonymous", help="Creator name for metadata")
    upload_parser.add_argument("--description", default="Game patch generated by gpatcher", help="Description for metadata")

    # search
    search_parser = subparsers.add_parser("search", help="Searches the Internet Archive for gpatcher bundles")
    search_parser.add_argument("query", nargs="+", help="Search query (e.g. game name)")

    # fetch
    fetch_parser = subparsers.add_parser("fetch", help="Downloads a patch package from the Internet Archive")
    fetch_parser.add_argument("--game", required=True, help="Game slug")
    fetch_parser.add_argument("--from", dest="from_ver", required=True, help="Starting version")
    fetch_parser.add_argument("--to", dest="to_ver", required=True, help="Target version")
    fetch_parser.add_argument("--out", default=".", help="Output directory")

    # verify
    verify_parser = subparsers.add_parser("verify", help="Verifies that an install directory matches a snapshot")
    verify_parser.add_argument("--install", required=True, help="Directory to verify")
    verify_parser.add_argument("--against", required=True, help="Path to manifest.json or patch ZIP")

    # update
    update_parser = subparsers.add_parser("update", help="Update gpatcher to the latest release version")
    update_parser.add_argument("--force", action="store_true", help="Force reinstall of the latest version even if up-to-date")

    # doctor
    subparsers.add_parser("doctor", help="Performs system diagnostics check on dependencies")

    # ui
    subparsers.add_parser("ui", help="Launches the interactive menu dashboard")

    # help
    subparsers.add_parser("help", help="Show this help message")

    if args[0] in ("-h", "--help", "help"):
        parser.print_help()
        return 0

    try:
        parsed_args = parser.parse_args(args)
    except SystemExit as e:
        return e.code

    try:
        if parsed_args.command == "create":
            excludes = []
            if parsed_args.exclude:
                excludes = [x.strip() for x in re.split(r'[,;]', parsed_args.exclude) if x.strip()]
            invoke_create(
                old_dir=parsed_args.old,
                new_dir=parsed_args.new,
                game=parsed_args.game,
                old_ver=parsed_args.old_ver,
                new_ver=parsed_args.new_ver,
                out_dir=parsed_args.out,
                exclude=excludes
            )
        elif parsed_args.command == "apply":
            invoke_apply(
                patch_path=parsed_args.patch,
                target=parsed_args.target,
                dry_run=parsed_args.dry_run,
                no_backup=parsed_args.no_backup,
                keep_backup=parsed_args.keep_backup
            )
        elif parsed_args.command == "restore":
            invoke_restore(
                target=parsed_args.target,
                backup=parsed_args.backup,
                keep_backup=parsed_args.keep_backup
            )
        elif parsed_args.command == "upload":
            invoke_upload(
                bundle_path=parsed_args.patch,
                creator=parsed_args.creator,
                description=parsed_args.description
            )
        elif parsed_args.command == "search":
            query_str = " ".join(parsed_args.query)
            invoke_search(query_str)
        elif parsed_args.command == "fetch":
            invoke_fetch(
                game_slug=parsed_args.game,
                from_ver=parsed_args.from_ver,
                to_ver=parsed_args.to_ver,
                out_dir=parsed_args.out
            )
        elif parsed_args.command == "verify":
            invoke_verify(
                install_dir=parsed_args.install,
                against_path=parsed_args.against
            )
        elif parsed_args.command == "doctor":
            invoke_doctor()
        elif parsed_args.command == "update":
            invoke_update(force=parsed_args.force)
        elif parsed_args.command == "ui":
            invoke_interactive_menu()
        else:
            parser.print_help()
            return 1
        return 0
    except Exception as e:
        log_err(str(e))
        return 1

if __name__ == '__main__':
    sys.exit(main())
