function Get-IAIdentifier {
    param(
        [Parameter(Mandatory)][string]$Slug,
        [Parameter(Mandatory)][string]$OldVer,
        [Parameter(Mandatory)][string]$NewVer
    )
    $clean = {
        param($v)
        ($v.ToLowerInvariant() -replace '[^a-z0-9.]+','-').Trim('-')
    }
    $id = "gpatcher-$Slug-$(& $clean $OldVer)-to-$(& $clean $NewVer)"
    if ($id.Length -gt 100) { $id = $id.Substring(0,100).TrimEnd('-') }
    $id
}

function Test-IACli {
    if (-not (Test-CommandExists 'ia')) {
        throw "'ia' CLI not found. Install: pip install internetarchive, then run 'ia configure'."
    }
}

function Invoke-IAUpload {
    param(
        [Parameter(Mandatory)][string]$BundlePath,
        [string]$Creator = 'anonymous',
        [string]$Description = 'Game patch generated by gpatcher'
    )
    Test-IACli
    if (-not (Test-Path -LiteralPath $BundlePath)) { throw "Bundle not found: $BundlePath" }

    $staging = New-TempDir 'gpatcher-iaread'
    try {
        Expand-Dir -ZipPath $BundlePath -DestDir $staging
        $m = Read-ManifestFile -Path (Join-Path $staging 'manifest.json')
    } finally {
        Remove-PathSafe $staging
    }

    $id = Get-IAIdentifier -Slug $m.game_slug -OldVer $m.old_version -NewVer $m.new_version
    $title = "$($m.game) patch: $($m.old_version) -> $($m.new_version)"
    $subjects = @('gpatcher','popayarip','game-patch',$m.game_slug,"version-$($m.old_version)","version-$($m.new_version)")

    $iaArgs = @(
        'upload', $id, $BundlePath,
        "--metadata=title:$title",
        "--metadata=description:$Description",
        "--metadata=creator:$Creator",
        "--metadata=mediatype:data",
        "--metadata=collection:opensource"
    )
    foreach ($s in $subjects) { $iaArgs += "--metadata=subject:$s" }

    LogInfo "Uploading to archive.org as $id"
    & ia @iaArgs
    if ($LASTEXITCODE -ne 0) { throw "ia upload failed (exit $LASTEXITCODE)" }
    LogOk "https://archive.org/details/$id"
    $id
}

function Invoke-IASearch {
    param([Parameter(Mandatory)][string]$Query)
    Test-IACli
    $q = "(subject:gpatcher OR subject:popayarip) AND ($Query)"
    & ia search $q --field=identifier --field=title
    if ($LASTEXITCODE -ne 0) { throw "ia search failed (exit $LASTEXITCODE)" }
}

function Test-IAItemExists {
    param([Parameter(Mandatory)][string]$Id)
    $res = (& ia search "identifier:$Id" 2>$null) | Out-String
    return (-not [string]::IsNullOrWhiteSpace($res))
}

function Invoke-IAFetch {
    param(
        [Parameter(Mandatory)][string]$GameSlug,
        [Parameter(Mandatory)][string]$FromVer,
        [Parameter(Mandatory)][string]$ToVer,
        [string]$OutDir = '.'
    )
    Test-IACli

    $clean = {
        param($v)
        ($v.ToLowerInvariant() -replace '[^a-z0-9.]+','-').Trim('-')
    }

    $id = "gpatcher-$GameSlug-$(& $clean $FromVer)-to-$(& $clean $ToVer)"
    if ($id.Length -gt 100) { $id = $id.Substring(0,100).TrimEnd('-') }

    $targetId = $id
    if (-not (Test-IAItemExists -Id $id)) {
        $fallbackId = "popayarip-$GameSlug-$(& $clean $FromVer)-to-$(& $clean $ToVer)"
        if ($fallbackId.Length -gt 100) { $fallbackId = $fallbackId.Substring(0,100).TrimEnd('-') }
        
        if (Test-IAItemExists -Id $fallbackId) {
            LogWarn "gpatcher release not found. Falling back to legacy release identifier: $fallbackId"
            $targetId = $fallbackId
        } else {
            throw "No patch release found on archive.org for either '$id' or legacy '$fallbackId'."
        }
    }

    if (-not (Test-Path -LiteralPath $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }
    LogInfo "Fetching $targetId"
    & ia download $targetId --destdir=$OutDir
    if ($LASTEXITCODE -ne 0) { throw "ia download failed for $targetId (exit $LASTEXITCODE)" }
}
