import os
import re
import sys
import internetarchive
from gpatcher.core.common import log_info, log_ok, log_warn, new_temp_dir, remove_path_safe
from gpatcher.core.manifest import read_manifest_file
from gpatcher.tools.archive import expand_dir

def get_ia_identifier(slug: str, old_ver: str, new_ver: str) -> str:
    """Generates the Internet Archive identifier for the patch package."""
    clean = lambda v: re.sub(r'[^a-z0-9.]+', '-', v.lower()).strip('-')
    identifier = f"gpatcher-{slug}-{clean(old_ver)}-to-{clean(new_ver)}"
    if len(identifier) > 100:
        identifier = identifier[:100].rstrip('-')
    return identifier

def invoke_upload(bundle_path: str, creator: str = 'anonymous', description: str = 'Game patch generated by gpatcher') -> str:
    """Uploads a game patch bundle to the Internet Archive with metadata."""
    if not os.path.exists(bundle_path):
        raise FileNotFoundError(f"Bundle file not found: {bundle_path}")

    staging = new_temp_dir('gpatcher-iaread')
    try:
        expand_dir(bundle_path, staging)
        manifest_path = os.path.join(staging, 'manifest.json')
        if not os.path.exists(manifest_path):
            raise FileNotFoundError(f"Manifest not found in bundle: {bundle_path}")
        m = read_manifest_file(manifest_path)
    finally:
        remove_path_safe(staging)

    slug = m['game_slug']
    identifier = get_ia_identifier(slug, m['old_version'], m['new_version'])
    title = f"{m['game']} patch: {m['old_version']} -> {m['new_version']}"
    subjects = ['gpatcher', 'popayarip', 'game-patch', slug, f"version-{m['old_version']}", f"version-{m['new_version']}"]

    metadata = {
        'title': title,
        'description': description,
        'creator': creator,
        'mediatype': 'data',
        'collection': 'opensource',
        'subject': subjects
    }

    log_info(f"Uploading to archive.org as {identifier}...")
    try:
        internetarchive.upload(identifier, files=[bundle_path], metadata=metadata)
        log_ok(f"Uploaded successfully!")
        log_ok(f"https://archive.org/details/{identifier}")
        return identifier
    except Exception as e:
        raise RuntimeError(f"Internet Archive upload failed: {e}")

def invoke_search(query: str):
    """Searches the Internet Archive for gpatcher bundles matching the query."""
    query_str = f"(subject:gpatcher OR subject:popayarip) AND ({query})"
    log_info(f"Searching Internet Archive...")
    try:
        results = internetarchive.search_items(query_str, fields=['identifier', 'title'])
        found_any = False
        for r in results:
            identifier = r.get('identifier')
            title = r.get('title', 'No Title')
            print(f"Found: {identifier} - {title}")
            found_any = True
        if not found_any:
            log_info(f"No patches found for '{query}'.")
    except Exception as e:
        raise RuntimeError(f"Internet Archive search failed: {e}")

def invoke_fetch(game_slug: str, from_ver: str, to_ver: str, out_dir: str = '.'):
    """Downloads a patch package matching the game slug and versions from the Internet Archive."""
    clean = lambda v: re.sub(r'[^a-z0-9.]+', '-', v.lower()).strip('-')
    target_id = f"gpatcher-{game_slug}-{clean(from_ver)}-to-{clean(to_ver)}"
    if len(target_id) > 100:
        target_id = target_id[:100].rstrip('-')

    log_info(f"Checking for patch {target_id}...")
    item = internetarchive.get_item(target_id)
    if not item.exists:
        fallback_id = f"popayarip-{game_slug}-{clean(from_ver)}-to-{clean(to_ver)}"
        if len(fallback_id) > 100:
            fallback_id = fallback_id[:100].rstrip('-')
        log_warn(f"Release '{target_id}' not found. Checking fallback legacy release: {fallback_id}...")
        item = internetarchive.get_item(fallback_id)
        if not item.exists:
            raise RuntimeError(f"No patch release found on archive.org for either '{target_id}' or legacy '{fallback_id}'")
        target_id = fallback_id

    if not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    log_info(f"Downloading patch item {target_id} to {out_dir}...")
    try:
        item.download(destdir=out_dir)
        log_ok(f"Successfully downloaded patch folder to: {os.path.join(out_dir, target_id)}")
    except Exception as e:
        raise RuntimeError(f"Internet Archive download failed for {target_id}: {e}")
